name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: check-application
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=rafaelmvale_ci_sonarcloud
            -Dsonar.organization=rafaelmvale
            -Dsonar.host.url=https://sonarcloud.io
