name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: check-application
    steps:
      - name: SonarCloud Scan - Setup
        uses: SonarSource/sonarcloud-github-action@master

      - name: SonarCloud Scan - Analysis
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          CI_SONARCLOUD: ${{ secrets.CI_SONARCLOUD }}
        with:
          args: >
            -Dsonar.projectKey=rafaelmvale_ci_sonarcloud
            -Dsonar.organization=rafaelmvale
            -Dsonar.host.url=https://sonarcloud.io
