name: CI Pipeline

on: 
  pull_request:
    branches:
      = main  
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=rafaelmvale_ci_sonarcloud
            -Dsonar.organization=rafaelmvale
            -Dsonar.host.url=https://sonarcloud.io
